import { firebaseService } from './third-party/firebase.service';
import { referralService } from './referral.service';
import { UserDocument } from '../types';
import { logger } from '../utils/logger';
import { NotFoundError, ConflictError } from '../utils/errors';

class UserService {
  private readonly COLLECTION = 'users';

  async createUser(
    uid: string,
    email: string,
    firstName: string,
    lastName: string,
    referredBy?: string
  ): Promise<void> {
    const db = firebaseService.getFirestore();

    // Check if user already exists
    const existingUser = await db.collection(this.COLLECTION).doc(uid).get();
    if (existingUser.exists) {
      throw new ConflictError('User already exists');
    }

    // Validate referral code if provided
    let referrerUid: string | undefined;
    if (referredBy) {
      const referrer = await referralService.getUserByReferralCode(referredBy);
      if (!referrer) {
        throw new NotFoundError('Invalid referral code');
      }
      referrerUid = referrer.uid;
    }

    const userData: UserDocument = {
      email,
      firstName,
      lastName,
      referralCode: '', // Will be generated by background job
      referredBy: referrerUid,
      referralCount: 0,
      createdAt: new Date() as any,
      updatedAt: new Date() as any,
      isActive: true,
    };

    try {
      await db.collection(this.COLLECTION).doc(uid).set(userData);
      logger.info(`User created: ${uid}`);
    } catch (error) {
      logger.error('Failed to create user document', error);
      throw error;
    }
  }

  async getUser(uid: string) {
    const db = firebaseService.getFirestore();
    const userDoc = await db.collection(this.COLLECTION).doc(uid).get();

    if (!userDoc.exists) {
      return null;
    }

    return { uid, ...userDoc.data() };
  }

  async updateUser(uid: string, data: Partial<UserDocument>): Promise<void> {
    const db = firebaseService.getFirestore();
    
    try {
      await db.collection(this.COLLECTION).doc(uid).update({
        ...data,
        updatedAt: new Date(),
      });
      logger.info(`User updated: ${uid}`);
    } catch (error) {
      logger.error('Failed to update user', error);
      throw error;
    }
  }

  async deactivateUser(uid: string): Promise<void> {
    await this.updateUser(uid, { isActive: false });
    logger.info(`User deactivated: ${uid}`);
  }

  async activateUser(uid: string): Promise<void> {
    await this.updateUser(uid, { isActive: true });
    logger.info(`User activated: ${uid}`);
  }

  async getUserByEmail(email: string) {
    const db = firebaseService.getFirestore();
    const snapshot = await db
      .collection(this.COLLECTION)
      .where('email', '==', email)
      .limit(1)
      .get();

    if (snapshot.empty) {
      return null;
    }

    const doc = snapshot.docs[0];
    return { uid: doc.id, ...doc.data() };
  }
}

export const userService = new UserService();